server:
  port: 8080
spring:
  application:
    name: InitialAssessment
  datasource:
    url: jdbc:mysql://localhost:3306/initial_assessment
    username: sa
    password: sa
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

